server:
  port: 8080
  servlet:
    context-path: /idle
spring:
  main:
    allow-circular-references: true
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
  datasource:
    #    mysql配置   mysql6以前com.ysql.jdbc.Driver驱动 6以后com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/idle?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: idle
    password: '12345678'
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 100
      max-wait: 60000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      filters: stat
      use-global-data-source-stat: true
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
pagehelper:
  helper-dialect: mysql
logging:
  config: classpath:/log4j2-config.xml
  level:
    tech.idle.dao: trace
#自定义常量
props:
  project:
    #项目顶级文件目录
    #    rootFilePath: '/home/back/data/idle/'
    rootFilePath: 'D://fileTest/idle/'
    #下载目录
    download:
    #上传目录
    upload:
    #临时文件夹
    temp: 'temp/'